version: '2'
services:
  apache:
    scale: 1
    start_on_create: true
  webbackend:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: apache
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  Varnish:
    scale: 1
    start_on_create: true
